name: docker pipeline
  
on:
  push:
    branches: ['master']

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
#      - name: Run image
#        run: docker run -d -p 8080:80 leahtara/portfolio
