name: publish image to docker hub
on:
  [workflow_dispatch]

jobs:
  publish-image: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t leahtara/portfolio:latest
      - name: publish
        run: | 
          docker push leahtara/portfolio:latest
